language: node_js
node_js:
  - 12
before_install:
  - curl -sL https://firebase.tools | bash
install:
  - rm -rf node_modules
  - rm package-lock.json
  - npm install
  - npm rebuild
script:
  - npm test
