language: node_js
node_js:
  - 8
before_install:
  - curl -sL https://firebase.tools | bash
install:
  - rm -rf node_modules
  - rm package-lock.json
  - npm install
  - npm rebuild --target=8.17.0 --target_platform=linux --target_arch=x64
script:
  - npm test
